<?php
use App\Http\Controllers\Api\{AuthController,CategoryController,CourseController,CourseModerationController,CoursePlayerController,CurriculumController,EnrollmentController,EnrollmentStatisticsController,InstructorApprovalController,InstructorCurriculumController,InstructorQuizController,LessonContentController,LessonPreviewController,MediaDeliveryController,PublicCatalogController,ReviewController,ReviewModerationController,StudentQuizController};
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;

Route::middleware('guest')->group(function () {
    Route::post('/register', [AuthController::class, 'register']);
    Route::post('/login', [AuthController::class, 'login']);
});
Route::get('/categories', [PublicCatalogController::class, 'categories']);
Route::get('/courses', [PublicCatalogController::class, 'index']);
Route::get('/courses/{slug}', [PublicCatalogController::class, 'show']);
Route::get('/courses/{course}/reviews', [ReviewController::class, 'index']);
Route::get('/courses/{course}/rating', [ReviewController::class, 'statistics']);
Route::get('/preview/lessons/{lesson}', [LessonPreviewController::class, 'show']);
Route::get('/preview/lessons/{lesson}/video', [LessonPreviewController::class, 'video']);

Route::middleware('auth:sanctum')->group(function () {
    Route::get('/user', fn (Request $request) => $request->user()->load('roles:id,name'));
    Route::post('/logout', [AuthController::class, 'logout']);
    Route::get('/manage/courses', [CourseController::class, 'index']);
    Route::post('/manage/courses', [CourseController::class, 'store']);
    Route::put('/manage/courses/{course}', [CourseController::class, 'update']);
    Route::delete('/manage/courses/{course}', [CourseController::class, 'destroy']);
    Route::post('/manage/courses/{course}/submit', [CourseController::class, 'submit']);
    Route::post('/instructor/apply', [InstructorApprovalController::class, 'apply']);
    Route::get('/courses/{course}/my-review', [ReviewController::class, 'own']);
    Route::post('/courses/{course}/reviews', [ReviewController::class, 'store']);
    Route::put('/reviews/{review}', [ReviewController::class, 'update']);
    Route::delete('/reviews/{review}', [ReviewController::class, 'destroy']);
    Route::get('/enrollments', [EnrollmentController::class, 'index']);
    Route::post('/courses/{course}/enroll', [EnrollmentController::class, 'store']);
    Route::get('/enrollments/{enrollment}/progress', [EnrollmentController::class, 'show']);
    Route::patch('/enrollments/{enrollment}/cancel', [EnrollmentController::class, 'cancel']);
    Route::put('/enrollments/{enrollment}/lessons/{lesson}/progress', [EnrollmentController::class, 'updateProgress']);
    Route::get('/manage/courses/{course}/enrollment-statistics', [EnrollmentStatisticsController::class, 'show']);
    Route::get('/manage/courses/{course}/curriculum', [InstructorCurriculumController::class, 'show']);
    Route::post('/manage/courses/{course}/sections', [CurriculumController::class, 'storeSection']);
    Route::put('/manage/sections/{section}', [CurriculumController::class, 'updateSection']);
    Route::delete('/manage/sections/{section}', [CurriculumController::class, 'destroySection']);
    Route::post('/manage/sections/{section}/lessons', [CurriculumController::class, 'storeLesson']);
    Route::put('/manage/lessons/{lesson}', [CurriculumController::class, 'updateLesson']);
    Route::delete('/manage/lessons/{lesson}', [CurriculumController::class, 'destroyLesson']);
    Route::put('/manage/lessons/{lesson}/content', [LessonContentController::class, 'updateText']);
    Route::post('/manage/lessons/{lesson}/video', [LessonContentController::class, 'storeVideo']);
    Route::delete('/manage/lessons/{lesson}/video', [LessonContentController::class, 'destroyVideo']);
    Route::post('/manage/lessons/{lesson}/attachments', [LessonContentController::class, 'storeAttachment']);
    Route::delete('/manage/attachments/{attachment}', [LessonContentController::class, 'destroyAttachment']);
    Route::get('/manage/lessons/{lesson}/quiz', [InstructorQuizController::class, 'show']);
    Route::post('/manage/lessons/{lesson}/quiz', [InstructorQuizController::class, 'store']);
    Route::put('/manage/quizzes/{quiz}', [InstructorQuizController::class, 'update']);
    Route::post('/manage/quizzes/{quiz}/questions', [InstructorQuizController::class, 'storeQuestion']);
    Route::put('/manage/questions/{question}', [InstructorQuizController::class, 'updateQuestion']);
    Route::delete('/manage/questions/{question}', [InstructorQuizController::class, 'destroyQuestion']);
    Route::put('/manage/quizzes/{quiz}/reorder', [InstructorQuizController::class, 'reorder']);
    Route::post('/manage/quizzes/{quiz}/publish', [InstructorQuizController::class, 'publish']);
    Route::get('/manage/quizzes/{quiz}/preview', [InstructorQuizController::class, 'preview']);
    Route::get('/learning/enrollments/{enrollment}', [CoursePlayerController::class, 'enrollment']);
    Route::get('/learning/lessons/{lesson}', [CoursePlayerController::class, 'lesson']);
    Route::get('/learning/lessons/{lesson}/video', [MediaDeliveryController::class, 'video'])->name('lessons.video.stream');
    Route::get('/learning/attachments/{attachment}', [MediaDeliveryController::class, 'attachment'])->name('attachments.download');
    Route::get('/learning/lessons/{lesson}/quiz', [StudentQuizController::class, 'show']);
    Route::post('/learning/quizzes/{quiz}/attempts', [StudentQuizController::class, 'start']);
    Route::get('/learning/quizzes/{quiz}/attempts', [StudentQuizController::class, 'index']);
    Route::get('/learning/quiz-attempts/{attempt}', [StudentQuizController::class, 'showAttempt']);
    Route::post('/learning/quiz-attempts/{attempt}/submit', [StudentQuizController::class, 'submit']);
    Route::apiResource('/admin/categories', CategoryController::class)->except('show');
    Route::post('/admin/courses/{course}/approve', [CourseModerationController::class, 'approve']);
    Route::post('/admin/courses/{course}/reject', [CourseModerationController::class, 'reject']);
    Route::post('/admin/courses/{course}/archive', [CourseModerationController::class, 'archive']);
    Route::patch('/admin/instructors/{user}/status', [InstructorApprovalController::class, 'update']);
    Route::get('/admin/instructors', [InstructorApprovalController::class, 'index']);
    Route::get('/manage/courses/{course}/reviews', [ReviewModerationController::class, 'course']);
    Route::get('/admin/reviews', [ReviewModerationController::class, 'index']);
    Route::patch('/admin/reviews/{review}', [ReviewModerationController::class, 'update']);
});
