import { useEffect, useState } from 'react';
import { Star, Trash2 } from 'lucide-react';
import api from '../api/client';
import useAuth from '../context/useAuth';

const message=e=>e.response?.data?.message||Object.values(e.response?.data?.errors||{})[0]?.[0]||'The review action failed.';
export default function CourseReviews({course}){
  const {user,isAuthenticated}=useAuth(),student=user?.roles?.some(role=>role.name==='student');
  const [reviews,setReviews]=useState([]),[stats,setStats]=useState({average_rating:0,review_count:0,distribution:{}}),[own,setOwn]=useState(null),[rating,setRating]=useState(5),[text,setText]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const load=async()=>{const [list,summary]=await Promise.all([api.get(`/api/courses/${course.id}/reviews`),api.get(`/api/courses/${course.id}/rating`)]);setReviews(list.data.data||[]);setStats(summary.data.data);if(isAuthenticated&&student){const mine=await api.get(`/api/courses/${course.id}/my-review`);setOwn(mine.data.data);if(mine.data.data){setRating(mine.data.data.rating);setText(mine.data.data.review_text);}}};
  useEffect(()=>{load().catch(()=>setNotice('Reviews could not be loaded.'));},[course.id,isAuthenticated,student]); // eslint-disable-line react-hooks/exhaustive-deps
  const submit=async e=>{e.preventDefault();setBusy(true);setNotice('');try{if(own){await api.put(`/api/reviews/${own.id}`,{rating,review_text:text});}else{await api.post(`/api/courses/${course.id}/reviews`,{rating,review_text:text});}setNotice(own?'Your review was updated.':'Your review was published.');await load();}catch(x){setNotice(message(x));}finally{setBusy(false);}};
  const remove=async()=>{if(!window.confirm('Delete your review?'))return;try{await api.delete(`/api/reviews/${own.id}`);setOwn(null);setText('');setRating(5);await load();}catch(e){setNotice(message(e));}};
  return <section className="border-t border-slate-200 py-20"><div className="section-shell"><div className="grid gap-12 lg:grid-cols-[320px_1fr]"><aside><p className="section-kicker">Course feedback</p><h2 className="section-title">Ratings & reviews</h2><div className="mt-8 flex items-end gap-3"><strong className="text-6xl text-slate-950">{Number(stats.average_rating).toFixed(1)}</strong><div><Stars value={Math.round(stats.average_rating)}/><p className="mt-1 text-sm text-slate-500">{stats.review_count} reviews</p></div></div><div className="mt-8 space-y-3">{[5,4,3,2,1].map(star=>{const count=stats.distribution?.[star]||0,width=stats.review_count?count/stats.review_count*100:0;return <div key={star} className="flex items-center gap-3 text-sm"><span>{star}</span><div className="h-2 flex-1 rounded-full bg-slate-100"><div className="h-full rounded-full bg-primary" style={{width:`${width}%`}}/></div><span className="w-6 text-right text-slate-500">{count}</span></div>})}</div></aside><div>{student&&<form onSubmit={submit} className="mb-10 rounded-2xl border border-slate-200 bg-slate-50 p-6"><div className="flex justify-between"><h3 className="text-xl font-bold">{own?'Edit your review':'Share your experience'}</h3>{own&&<button type="button" onClick={remove} className="text-red-600" aria-label="Delete review"><Trash2/></button>}</div><label className="mt-5 block text-sm font-semibold">Your rating</label><div className="mt-2 flex gap-1">{[1,2,3,4,5].map(value=><button type="button" key={value} onClick={()=>setRating(value)} aria-label={`${value} stars`}><Star className={`h-7 w-7 ${value<=rating?'fill-amber-400 text-amber-400':'text-slate-300'}`}/></button>)}</div><label className="mt-5 block text-sm font-semibold" htmlFor="review-text">Review</label><textarea id="review-text" className="field mt-2 min-h-32" value={text} onChange={e=>setText(e.target.value)} minLength={10} maxLength={5000} required placeholder="What did you find useful?"/><button disabled={busy} className="action mt-4">{busy?'Saving...':own?'Update review':'Publish review'}</button>{notice&&<p className="notice">{notice}</p>}</form>}<div className="space-y-5">{reviews.length?reviews.map(review=><article key={review.id} className="rounded-2xl border border-slate-200 p-6"><div className="flex justify-between"><div><strong>{review.user?.name}</strong><Stars value={review.rating}/></div><time className="text-sm text-slate-400">{new Date(review.created_at).toLocaleDateString()}</time></div><p className="mt-4 leading-7 text-slate-600">{review.review_text}</p></article>):<div className="rounded-2xl bg-slate-50 p-8 text-center text-slate-500">No published reviews yet.</div>}</div></div></div></div></section>;
}
function Stars({value}){return <div className="mt-1 flex gap-0.5 text-amber-400">{[1,2,3,4,5].map(star=><Star key={star} className={`h-4 w-4 ${star<=value?'fill-current':''}`}/>)}</div>}
