import { useEffect, useState } from 'react';
import api from '../api/client';

export default function QuizPlayer({ lesson, onProgressChanged }) {
  const [quiz, setQuiz] = useState(null); const [attempt, setAttempt] = useState(null);
  const [answers, setAnswers] = useState({}); const [error, setError] = useState(''); const [seconds, setSeconds] = useState(null);
  useEffect(() => { api.get(`/api/learning/lessons/${lesson.id}/quiz`).then(async ({ data }) => { setQuiz(data.data); const history = await api.get(`/api/learning/quizzes/${data.data.id}/attempts`); const active = history.data.data?.find(item => item.status === 'in_progress'); if (active) setAttempt(active); }).catch(() => setError('This quiz is not available.')); }, [lesson.id]);
  useEffect(() => { if (!attempt?.expires_at || attempt.status !== 'in_progress') return; const tick = () => setSeconds(Math.max(0, Math.floor((new Date(attempt.expires_at) - Date.now()) / 1000))); tick(); const timer = setInterval(tick, 1000); return () => clearInterval(timer); }, [attempt]);
  const start = async () => { try { const { data } = await api.post(`/api/learning/quizzes/${quiz.id}/attempts`); setAttempt(data.data); } catch (e) { setError(e.response?.data?.message || 'Unable to start attempt.'); } };
  const submit = async () => { if (!window.confirm('Submit this attempt for grading?')) return; try { const payload = Object.entries(answers).map(([question_id, answer_id]) => ({ question_id: Number(question_id), answer_id })); const { data } = await api.post(`/api/learning/quiz-attempts/${attempt.id}/submit`, { answers: payload }); setAttempt(data.data); await onProgressChanged?.(); } catch (e) { setError(e.response?.data?.message || 'Submission failed.'); } };
  if (error) return <p className="p-4 bg-red-50 text-red-700 rounded-xl">{error}</p>;
  if (!quiz) return <p>Loading quiz…</p>;
  if (attempt && attempt.status !== 'in_progress') return <div className="text-center p-8 border rounded-2xl"><h3 className="text-2xl font-bold">{attempt.status === 'expired' ? 'Time expired' : attempt.passed ? 'Passed' : 'Not passed'}</h3><p className="mt-3 text-lg">Score: {attempt.score} / {attempt.maximum_score} ({attempt.percentage}%)</p>{!attempt.passed && attempt.attempt_number < quiz.maximum_attempts && <button onClick={() => { setAttempt(null); setAnswers({}); }} className="mt-5 px-4 py-2 bg-primary text-white rounded-lg">Try again</button>}</div>;
  if (!attempt) return <div className="p-6 border rounded-2xl"><h3 className="text-xl font-bold">{quiz.title}</h3><p className="mt-2">{quiz.description}</p><p className="mt-4 text-sm">Pass: {quiz.passing_score_percentage}% · Attempts remaining: {quiz.attempts_remaining}{quiz.time_limit_minutes ? ` · ${quiz.time_limit_minutes} minutes` : ''}</p><button disabled={!quiz.attempts_remaining} onClick={start} className="mt-5 px-4 py-2 bg-primary text-white rounded-lg disabled:opacity-50">Start assessment</button></div>;
  const activeQuiz = attempt.quiz || quiz;
  return <div><div className="flex justify-between mb-5"><h3 className="text-xl font-bold">Attempt {attempt.attempt_number}</h3>{seconds !== null && <span className="font-mono">{Math.floor(seconds / 60)}:{String(seconds % 60).padStart(2, '0')}</span>}</div>{activeQuiz.questions.map((question, index) => <fieldset key={question.id} className="mb-6 border rounded-xl p-4"><legend className="font-semibold px-2">{index + 1}. {question.question_text}</legend>{question.options.map(option => <label key={option.id} className="block mt-3 p-3 bg-slate-50 rounded-lg"><input type="radio" name={`q-${question.id}`} className="mr-3" checked={answers[question.id] === option.id} onChange={() => setAnswers({ ...answers, [question.id]: option.id })} />{option.option_text}</label>)}</fieldset>)}<button onClick={submit} className="px-5 py-2 bg-primary text-white rounded-lg">Submit answers</button></div>;
}
