import { useEffect, useState } from 'react';
import { Link } from 'react-router';
import api from '../api/client';

const message = error => error.response?.data?.message || Object.values(error.response?.data?.errors || {})[0]?.[0] || 'Action failed.';
const Box = ({ title, meta, children }) => <div className="mt-3 rounded-[1.25rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between gap-4"><h3 className="font-bold tracking-[-0.03em] text-slate-950">{title}</h3><small className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold uppercase tracking-[0.14em] text-slate-600">{meta}</small></div><div className="mt-4 flex flex-wrap gap-3 text-sm font-semibold">{children}</div></div>;

export function StudentDashboard({ user, refreshUser }) {
  const [items, setItems] = useState([]); const [notice, setNotice] = useState('');
  useEffect(() => { api.get('/api/enrollments').then(r => setItems(r.data.data || [])).catch(e => setNotice(message(e))); }, []);
  const apply = async () => { try { const { data } = await api.post('/api/instructor/apply'); setNotice(data.message); await refreshUser(); } catch (e) { setNotice(message(e)); } };
  return <><div className="flex justify-between"><h1 className="text-3xl font-bold">Welcome, {user.name}</h1>{user.instructor_status !== 'pending' && <button onClick={apply} className="action">Become an instructor</button>}</div>{notice && <p className="notice">{notice}</p>}<div className="grid md:grid-cols-2 gap-4 mt-6">{items.map(item => <Box key={item.id} title={item.course.title} meta={`${item.completion_percentage}%`}><Link to={`/learn/${item.id}`} className="text-accent">Continue learning →</Link></Box>)}</div></>;
}

export function InstructorDashboard({ user }) {
  const [courses, setCourses] = useState([]); const [categories, setCategories] = useState([]); const [notice, setNotice] = useState(''); const [stats, setStats] = useState({}); const [reviews, setReviews] = useState({});
  const [form, setForm] = useState({ category_id: '', title: '', short_description: '', description: '', level: 'beginner', language: 'English', duration: 0, type: 'free', price: 0 });
  const load = () => api.get('/api/manage/courses').then(r => setCourses(r.data.data || [])).catch(e => setNotice(message(e)));
  useEffect(() => { load(); api.get('/api/categories').then(r => { const list = r.data.data.flatMap(c => [c, ...(c.children || [])]); setCategories(list); setForm(f => ({ ...f, category_id: list[0]?.id || '' })); }); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const create = async e => { e.preventDefault(); try { await api.post('/api/manage/courses', form); await load(); setForm(f => ({ ...f, title: '', short_description: '', description: '' })); } catch (x) { setNotice(message(x)); } };
  const edit = async c => { const title = window.prompt('Course title', c.title); if (!title) return; try { await api.put(`/api/manage/courses/${c.id}`, { title }); await load(); } catch (e) { setNotice(message(e)); } };
  const submit = async c => { if (!window.confirm('Submit for admin review?')) return; try { await api.post(`/api/manage/courses/${c.id}/submit`); await load(); } catch (e) { setNotice(message(e)); } };
  const statistics = async c => { try { const { data } = await api.get(`/api/manage/courses/${c.id}/enrollment-statistics`); setStats(s => ({ ...s, [c.id]: data })); } catch (e) { setNotice(message(e)); } };
  const courseReviews = async c => { try { const { data } = await api.get(`/api/manage/courses/${c.id}/reviews`); setReviews(s => ({ ...s, [c.id]: data.data || [] })); } catch (e) { setNotice(message(e)); } };
  return <><h1 className="text-3xl font-bold">Instructor dashboard</h1><p>Status: {user.instructor_status}</p>{notice && <p className="notice">{notice}</p>}<form onSubmit={create} className="mt-6 grid md:grid-cols-2 gap-3 border rounded-2xl p-5"><h2 className="font-bold md:col-span-2">Create course</h2><input required className="field" placeholder="Title" value={form.title} onChange={e => setForm({ ...form, title: e.target.value })}/><select className="field" value={form.category_id} onChange={e => setForm({ ...form, category_id: Number(e.target.value) })}>{categories.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><input required className="field" placeholder="Short description" value={form.short_description} onChange={e => setForm({ ...form, short_description: e.target.value })}/><input required className="field" placeholder="Language" value={form.language} onChange={e => setForm({ ...form, language: e.target.value })}/><textarea required className="field md:col-span-2" placeholder="Description" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })}/><input type="number" min="0" className="field" value={form.duration} onChange={e => setForm({ ...form, duration: Number(e.target.value) })}/><button disabled={user.instructor_status !== 'approved'} className="action disabled:opacity-50">Create</button></form>{courses.map(c => <Box key={c.id} title={c.title} meta={c.status}><Link to={`/instructor/courses/${c.id}/curriculum`} className="text-accent">Curriculum</Link>{['draft','rejected'].includes(c.status) && <><button onClick={() => edit(c)}>Edit</button><button onClick={() => submit(c)}>Submit</button></>}<button onClick={() => statistics(c)}>Statistics</button><button onClick={() => courseReviews(c)}>Reviews</button>{stats[c.id] && <span>{stats[c.id].total} enrolled, {stats[c.id].completion_rate}% complete</span>}{reviews[c.id] && <div className="w-full space-y-2">{reviews[c.id].length ? reviews[c.id].map(review => <div key={review.id} className="rounded-xl bg-slate-50 p-3 text-sm"><strong>{review.user?.name} · {review.rating}/5</strong><p className="mt-1 text-slate-600">{review.review_text}</p></div>) : <p className="text-sm text-slate-500">No reviews yet.</p>}</div>}</Box>)}</>;
}

export function AdminDashboard() {
  const [courses,setCourses]=useState([]),[instructors,setInstructors]=useState([]),[categories,setCategories]=useState([]),[reviews,setReviews]=useState([]),[notice,setNotice]=useState('');
  const load=async()=>{try{const [c,i,g,r]=await Promise.all([api.get('/api/manage/courses'),api.get('/api/admin/instructors'),api.get('/api/admin/categories'),api.get('/api/admin/reviews')]);setCourses(c.data.data||[]);setInstructors(i.data.data||[]);setCategories(g.data.data||[]);setReviews(r.data.data||[]);}catch(e){setNotice(message(e));}};
  useEffect(()=>{load();},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const setInstructor=async(u,status)=>{const reason=status==='rejected'?window.prompt('Rejection reason'):null;if(status==='rejected'&&!reason)return;try{await api.patch(`/api/admin/instructors/${u.id}/status`,{status,reason});await load();}catch(e){setNotice(message(e));}};
  const moderate=async(c,action)=>{const reason=action==='reject'?window.prompt('Rejection reason'):null;if(action==='reject'&&!reason)return;try{await api.post(`/api/admin/courses/${c.id}/${action}`,{reason});await load();}catch(e){setNotice(message(e));}};
  const addCategory=async()=>{const name=window.prompt('Category name');if(!name)return;try{await api.post('/api/admin/categories',{name});await load();}catch(e){setNotice(message(e));}};
  const editCategory=async category=>{const name=window.prompt('Category name',category.name);if(!name)return;try{await api.put(`/api/admin/categories/${category.id}`,{name,parent_id:category.parent_id});await load();}catch(e){setNotice(message(e));}};
  const deleteCategory=async category=>{if(!window.confirm(`Delete ${category.name}?`))return;try{await api.delete(`/api/admin/categories/${category.id}`);await load();}catch(e){setNotice(message(e));}};
  const moderateReview=async(review,status)=>{try{await api.patch(`/api/admin/reviews/${review.id}`,{status});await load();}catch(e){setNotice(message(e));}};
  return <><h1 className="text-3xl font-bold">Admin dashboard</h1>{notice&&<p className="notice">{notice}</p>}<h2 className="mt-8 text-xl font-bold">Instructor approvals</h2>{instructors.map(u=><Box key={u.id} title={`${u.name} (${u.email})`} meta={u.instructor_status}><button onClick={()=>setInstructor(u,'approved')}>Approve</button><button onClick={()=>setInstructor(u,'rejected')}>Reject</button></Box>)}<h2 className="mt-8 text-xl font-bold">Course moderation</h2>{courses.map(c=><Box key={c.id} title={c.title} meta={c.status}>{c.status==='pending_review'&&<><button onClick={()=>moderate(c,'approve')}>Approve</button><button onClick={()=>moderate(c,'reject')}>Reject</button></>}{c.status==='published'&&<button onClick={()=>moderate(c,'archive')}>Archive</button>}</Box>)}<h2 className="mt-8 text-xl font-bold">Review moderation</h2>{reviews.map(review=><Box key={review.id} title={`${review.user?.name} · ${review.rating}/5`} meta={review.status}><p className="w-full text-sm text-slate-600">{review.review_text}</p>{review.status!=='published'&&<button onClick={()=>moderateReview(review,'published')}>Publish</button>}{review.status!=='hidden'&&<button onClick={()=>moderateReview(review,'hidden')} className="text-red-600">Hide</button>}</Box>)}<div className="mt-8 flex justify-between"><h2 className="text-xl font-bold">Categories ({categories.length})</h2><button onClick={addCategory} className="text-accent">Add category</button></div>{categories.map(category=><Box key={category.id} title={category.name} meta={category.is_active?'active':'inactive'}><button onClick={()=>editCategory(category)}>Edit</button><button onClick={()=>deleteCategory(category)} className="text-red-600">Delete</button></Box>)}</>;
}
