import { useEffect, useState } from 'react';
import { Link } from 'react-router';
import { useTranslation } from 'react-i18next';
import api from '../api/client';
import StudentLearningDashboard from './StudentLearningDashboard';

const Box = ({ title, meta, children }) => <div className="mt-3 rounded-[1.25rem] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between gap-4"><h3 className="font-bold tracking-[-0.03em] text-slate-950">{title}</h3><small className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold uppercase tracking-[0.14em] text-slate-600">{meta}</small></div><div className="mt-4 flex flex-wrap gap-3 text-sm font-semibold">{children}</div></div>;

export function LegacyStudentDashboard({ user, refreshUser }) {
  const { t } = useTranslation('dashboard'); const { t: tAi } = useTranslation('ai'); const [items, setItems] = useState([]); const [notice, setNotice] = useState('');
  const message = error => error.response?.data?.message || Object.values(error.response?.data?.errors || {})[0]?.[0] || t('actionFailed');
  useEffect(() => { api.get('/api/enrollments').then(response => setItems(response.data.data || [])).catch(error => setNotice(message(error))); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const apply = async () => { try { const { data } = await api.post('/api/instructor/apply'); setNotice(data.message); await refreshUser(); } catch (error) { setNotice(message(error)); } };
  return <><div className="flex flex-wrap justify-between gap-3"><h1 className="text-3xl font-bold">{t('welcome', { name: user.name })}</h1><div className="flex flex-wrap gap-2"><button type="button" onClick={() => window.dispatchEvent(new CustomEvent('thinkers-ai:open'))} className="action">{tAi('lessonActions.ask')}</button>{user.instructor_status !== 'pending' && <button onClick={apply} className="action">{t('becomeInstructor')}</button>}</div></div>{notice && <p className="notice">{notice}</p>}<div className="mt-6 grid gap-4 md:grid-cols-2">{items.map(item => <Box key={item.id} title={item.course.title} meta={`${item.completion_percentage}%`}><Link to={`/learn/${item.id}`} className="text-accent">{t('continue')} <span aria-hidden="true">→</span></Link></Box>)}</div></>;
}

export function StudentDashboard(props) { return <StudentLearningDashboard {...props}/>; }

export function InstructorDashboard({ user }) {
  const { t } = useTranslation('dashboard'); const [courses, setCourses] = useState([]); const [categories, setCategories] = useState([]); const [notice, setNotice] = useState(''); const [stats, setStats] = useState({}); const [reviews, setReviews] = useState({});
  const [form, setForm] = useState({ category_id: '', title: '', short_description: '', description: '', level: 'beginner', language: 'English', duration: 0, type: 'free', price: 0 });
  const message = error => error.response?.data?.message || Object.values(error.response?.data?.errors || {})[0]?.[0] || t('actionFailed');
  const load = () => api.get('/api/manage/courses').then(response => setCourses(response.data.data || [])).catch(error => setNotice(message(error)));
  useEffect(() => { load(); api.get('/api/categories').then(response => { const list = response.data.data.flatMap(category => [category, ...(category.children || [])]); setCategories(list); setForm(current => ({ ...current, category_id: list[0]?.id || '' })); }); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const create = async event => { event.preventDefault(); try { await api.post('/api/manage/courses', form); await load(); setForm(current => ({ ...current, title: '', short_description: '', description: '' })); } catch (error) { setNotice(message(error)); } };
  const edit = async course => { const title = window.prompt(t('courseTitle'), course.title); if (!title) return; try { await api.put(`/api/manage/courses/${course.id}`, { title }); await load(); } catch (error) { setNotice(message(error)); } };
  const submit = async course => { if (!window.confirm(t('submitReview'))) return; try { await api.post(`/api/manage/courses/${course.id}/submit`); await load(); } catch (error) { setNotice(message(error)); } };
  const statistics = async course => { try { const { data } = await api.get(`/api/manage/courses/${course.id}/enrollment-statistics`); setStats(current => ({ ...current, [course.id]: data })); } catch (error) { setNotice(message(error)); } };
  const courseReviews = async course => { try { const { data } = await api.get(`/api/manage/courses/${course.id}/reviews`); setReviews(current => ({ ...current, [course.id]: data.data || [] })); } catch (error) { setNotice(message(error)); } };
  return <><h1 className="text-3xl font-bold">{t('instructor')}</h1><p>{t('status', { status: user.instructor_status })}</p>{notice && <p className="notice">{notice}</p>}<form onSubmit={create} className="mt-6 grid gap-3 rounded-2xl border p-5 md:grid-cols-2"><h2 className="font-bold md:col-span-2">{t('createCourse')}</h2><input required className="field" placeholder={t('title')} value={form.title} onChange={event => setForm({ ...form, title: event.target.value })}/><select className="field" value={form.category_id} onChange={event => setForm({ ...form, category_id: Number(event.target.value) })}>{categories.map(category => <option key={category.id} value={category.id}>{category.name}</option>)}</select><input required className="field" placeholder={t('shortDescription')} value={form.short_description} onChange={event => setForm({ ...form, short_description: event.target.value })}/><input required className="field" placeholder={t('language')} value={form.language} onChange={event => setForm({ ...form, language: event.target.value })}/><textarea required className="field md:col-span-2" placeholder={t('description')} value={form.description} onChange={event => setForm({ ...form, description: event.target.value })}/><input type="number" min="0" aria-label={t('duration')} className="field" value={form.duration} onChange={event => setForm({ ...form, duration: Number(event.target.value) })}/><button disabled={user.instructor_status !== 'approved'} className="action disabled:opacity-50">{t('create')}</button></form>{courses.map(course => <Box key={course.id} title={course.title} meta={course.status}><Link to={`/instructor/courses/${course.id}/curriculum`} className="text-accent">{t('curriculum')}</Link>{['draft', 'rejected'].includes(course.status) && <><button onClick={() => edit(course)}>{t('edit')}</button><button onClick={() => submit(course)}>{t('submit')}</button></>}<button onClick={() => statistics(course)}>{t('statistics')}</button><button onClick={() => courseReviews(course)}>{t('reviews')}</button>{stats[course.id] && <span>{t('enrollmentStats', { total: stats[course.id].total, completion: stats[course.id].completion_rate })}</span>}{reviews[course.id] && <div className="w-full space-y-2">{reviews[course.id].length ? reviews[course.id].map(review => <div key={review.id} className="rounded-xl bg-slate-50 p-3 text-sm"><strong>{review.user?.name} · {review.rating}/5</strong><p className="mt-1 text-slate-600">{review.review_text}</p></div>) : <p className="text-sm text-slate-500">{t('noReviews')}</p>}</div>}</Box>)}</>;
}

export function AdminDashboard() {
  const { t } = useTranslation('dashboard'); const [courses, setCourses] = useState([]), [instructors, setInstructors] = useState([]), [categories, setCategories] = useState([]), [reviews, setReviews] = useState([]), [notice, setNotice] = useState('');
  const message = error => error.response?.data?.message || Object.values(error.response?.data?.errors || {})[0]?.[0] || t('actionFailed');
  const load = async () => { try { const [courseResponse, instructorResponse, categoryResponse, reviewResponse] = await Promise.all([api.get('/api/manage/courses'), api.get('/api/admin/instructors'), api.get('/api/admin/categories'), api.get('/api/admin/reviews')]); setCourses(courseResponse.data.data || []); setInstructors(instructorResponse.data.data || []); setCategories(categoryResponse.data.data || []); setReviews(reviewResponse.data.data || []); } catch (error) { setNotice(message(error)); } };
  useEffect(() => { load(); }, []); // eslint-disable-line react-hooks/exhaustive-deps
  const setInstructor = async (user, status) => { const reason = status === 'rejected' ? window.prompt(t('rejectionReason')) : null; if (status === 'rejected' && !reason) return; try { await api.patch(`/api/admin/instructors/${user.id}/status`, { status, reason }); await load(); } catch (error) { setNotice(message(error)); } };
  const moderate = async (course, action) => { const reason = action === 'reject' ? window.prompt(t('rejectionReason')) : null; if (action === 'reject' && !reason) return; try { await api.post(`/api/admin/courses/${course.id}/${action}`, { reason }); await load(); } catch (error) { setNotice(message(error)); } };
  const addCategory = async () => { const name = window.prompt(t('categoryName')); if (!name) return; try { await api.post('/api/admin/categories', { name }); await load(); } catch (error) { setNotice(message(error)); } };
  const editCategory = async category => { const name = window.prompt(t('categoryName'), category.name); if (!name) return; try { await api.put(`/api/admin/categories/${category.id}`, { name, parent_id: category.parent_id }); await load(); } catch (error) { setNotice(message(error)); } };
  const deleteCategory = async category => { if (!window.confirm(t('deleteCategory', { name: category.name }))) return; try { await api.delete(`/api/admin/categories/${category.id}`); await load(); } catch (error) { setNotice(message(error)); } };
  const moderateReview = async (review, status) => { try { await api.patch(`/api/admin/reviews/${review.id}`, { status }); await load(); } catch (error) { setNotice(message(error)); } };
  return <><h1 className="text-3xl font-bold">{t('admin')}</h1>{notice && <p className="notice">{notice}</p>}<h2 className="mt-8 text-xl font-bold">{t('instructorApprovals')}</h2>{instructors.map(user => <Box key={user.id} title={`${user.name} (${user.email})`} meta={user.instructor_status}><button onClick={() => setInstructor(user, 'approved')}>{t('approve')}</button><button onClick={() => setInstructor(user, 'rejected')}>{t('reject')}</button></Box>)}<h2 className="mt-8 text-xl font-bold">{t('courseModeration')}</h2>{courses.map(course => <Box key={course.id} title={course.title} meta={course.status}>{course.status === 'pending_review' && <><button onClick={() => moderate(course, 'approve')}>{t('approve')}</button><button onClick={() => moderate(course, 'reject')}>{t('reject')}</button></>}{course.status === 'published' && <button onClick={() => moderate(course, 'archive')}>{t('archive')}</button>}</Box>)}<h2 className="mt-8 text-xl font-bold">{t('reviewModeration')}</h2>{reviews.map(review => <Box key={review.id} title={`${review.user?.name} · ${review.rating}/5`} meta={review.status}><p className="w-full text-sm text-slate-600">{review.review_text}</p>{review.status !== 'published' && <button onClick={() => moderateReview(review, 'published')}>{t('publish')}</button>}{review.status !== 'hidden' && <button onClick={() => moderateReview(review, 'hidden')} className="text-red-600">{t('hide')}</button>}</Box>)}<div className="mt-8 flex justify-between"><h2 className="text-xl font-bold">{t('categories', { count: categories.length })}</h2><button onClick={addCategory} className="text-accent">{t('addCategory')}</button></div>{categories.map(category => <Box key={category.id} title={category.name} meta={t(category.is_active ? 'active' : 'inactive')}><button onClick={() => editCategory(category)}>{t('edit')}</button><button onClick={() => deleteCategory(category)} className="text-red-600">{t('common:actions.delete')}</button></Box>)}</>;
}
