import { CheckCircle2, UserCheck, XCircle } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { ConfirmDialog, EmptyState, ErrorState, PageSkeleton, StatusBadge } from './AdminUI';
import { useToast as useAdminToast } from '../../components/ui';
import { getInstructors, updateInstructor } from './adminApi';
import { PageHeading } from './AdminUsersPage';

export default function AdminInstructorsPage() {
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [decision, setDecision] = useState(null); const toast = useAdminToast();
  const load = useCallback(() => { setLoading(true); getInstructors({ status: 'pending' }).then(result => { setRows(result.data || []); setError(false); }).catch(() => setError(true)).finally(() => setLoading(false)); }, []);
  useEffect(load, [load]);
  const confirm = async () => { const reason = decision.status === 'rejected' ? window.prompt('Provide a rejection reason') : null; if (decision.status === 'rejected' && !reason) return; try { await updateInstructor(decision.user.id, { status: decision.status, reason }); toast({ message: `Instructor request ${decision.status}.` }); setDecision(null); await load(); } catch (requestError) { toast({ type: 'error', message: requestError.response?.data?.message || 'Unable to update request.' }); } };
  if (loading) return <PageSkeleton/>; if (error) return <ErrorState retry={load}/>;
  return <div className="space-y-6"><PageHeading title="Instructor requests" description="Review pending applications. Approval is the only path that grants instructor privileges."/>{rows.length ? <div className="grid gap-4 lg:grid-cols-2">{rows.map(user => <article key={user.id} className="rounded-2xl border bg-white p-6"><div className="flex items-start gap-4"><span className="grid h-12 w-12 place-items-center rounded-xl bg-amber-100"><UserCheck className="h-6 w-6 text-amber-700"/></span><div className="min-w-0 flex-1"><div className="flex items-center justify-between gap-3"><h3 className="truncate text-lg font-black">{user.name}</h3><StatusBadge value={user.instructor_status}/></div><p className="text-sm text-slate-500">{user.email}</p><p className="mt-2 text-xs text-slate-400">Applied account created {new Date(user.created_at).toLocaleDateString()}</p></div></div><div className="mt-6 flex gap-3 border-t pt-4"><button onClick={() => setDecision({ user, status: 'approved' })} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-emerald-600 px-4 py-2.5 font-bold text-white"><CheckCircle2 className="h-4 w-4"/>Approve</button><button onClick={() => setDecision({ user, status: 'rejected' })} className="inline-flex flex-1 items-center justify-center gap-2 rounded-xl bg-red-50 px-4 py-2.5 font-bold text-red-700"><XCircle className="h-4 w-4"/>Reject</button></div></article>)}</div> : <EmptyState title="No pending instructor applications" description="New applications will appear here for review."/>}<ConfirmDialog open={Boolean(decision)} title={`${decision?.status === 'approved' ? 'Approve' : 'Reject'} ${decision?.user.name}?`} description={decision?.status === 'approved' ? 'This grants instructor permissions and allows course creation.' : 'The applicant will remain a student and receive no instructor privileges.'} confirmLabel={decision?.status === 'approved' ? 'Approve instructor' : 'Reject request'} danger={decision?.status === 'rejected'} onConfirm={confirm} onClose={() => setDecision(null)}/></div>;
}
