import { FolderPlus, Pencil, Trash2 } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { ConfirmDialog, EmptyState, ErrorState, PageSkeleton, StatusBadge } from './AdminUI';
import { useToast as useAdminToast } from '../../components/ui';
import { createCategory, deleteCategory, getCategories, updateCategory } from './adminApi';
import { PageHeading } from './AdminUsersPage';

export default function AdminCategoriesPage() {
  const [rows, setRows] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(false); const [name, setName] = useState(''); const [editing, setEditing] = useState(null); const [deleting, setDeleting] = useState(null); const toast = useAdminToast();
  const load = useCallback(() => { getCategories().then(result => { setRows(result.data || []); setError(false); }).catch(() => setError(true)).finally(() => setLoading(false)); }, []);
  useEffect(load, [load]);
  const submit = async event => { event.preventDefault(); if (!name.trim()) return; try { if (editing) await updateCategory(editing.id, { name, parent_id: editing.parent_id }); else await createCategory({ name }); toast({ message: editing ? 'Category updated.' : 'Category created.' }); setName(''); setEditing(null); await load(); } catch (requestError) { toast({ type: 'error', message: requestError.response?.data?.message || 'Unable to save category.' }); } };
  const remove = async () => { try { await deleteCategory(deleting.id); toast({ message: 'Category deleted.' }); setDeleting(null); await load(); } catch (requestError) { toast({ type: 'error', message: requestError.response?.data?.message || 'Category is still in use.' }); } };
  if (loading) return <PageSkeleton/>; if (error) return <ErrorState retry={load}/>;
  return <div className="space-y-6"><PageHeading title="Categories" description="Maintain the taxonomy used across course discovery." action={<form onSubmit={submit} className="flex gap-2"><input className="field" value={name} onChange={e => setName(e.target.value)} placeholder={editing ? 'Rename category' : 'New category name'} required/><button className="action inline-flex items-center gap-2"><FolderPlus className="h-4 w-4"/>{editing ? 'Save' : 'Add'}</button>{editing && <button type="button" onClick={() => { setEditing(null); setName(''); }} className="rounded-xl border px-3">Cancel</button>}</form>}/>{rows.length ? <div className="overflow-hidden rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-500"><tr><th className="px-5 py-4">Category</th><th>Status</th><th>Order</th><th className="pr-5 text-right">Actions</th></tr></thead><tbody className="divide-y">{rows.map(category => <CategoryRow key={category.id} category={category} edit={item => { setEditing(item); setName(item.name); }} remove={setDeleting}/>)}</tbody></table></div> : <EmptyState title="No categories yet"/>}<ConfirmDialog open={Boolean(deleting)} title={`Delete ${deleting?.name}?`} description="Deletion is blocked by the API when courses still use this category." confirmLabel="Delete category" danger onConfirm={remove} onClose={() => setDeleting(null)}/></div>;
}
function CategoryRow({ category, edit, remove }) { return <><tr><td className="px-5 py-4 font-bold">{category.name}</td><td><StatusBadge value={category.is_active ? 'active' : 'inactive'}/></td><td>{category.sort_order}</td><td className="pr-5 text-right"><button onClick={() => edit(category)} className="rounded-lg p-2 hover:bg-slate-100" aria-label="Edit"><Pencil className="h-4 w-4"/></button><button onClick={() => remove(category)} className="rounded-lg p-2 text-red-600 hover:bg-red-50" aria-label="Delete"><Trash2 className="h-4 w-4"/></button></td></tr>{category.children?.map(child => <tr key={child.id} className="bg-slate-50/50"><td className="px-9 py-3 text-slate-600">↳ {child.name}</td><td><StatusBadge value={child.is_active ? 'active' : 'inactive'}/></td><td>{child.sort_order}</td><td className="pr-5 text-right"><button onClick={() => edit(child)} className="rounded-lg p-2"><Pencil className="h-4 w-4"/></button><button onClick={() => remove(child)} className="rounded-lg p-2 text-red-600"><Trash2 className="h-4 w-4"/></button></td></tr>)}</>; }
