import { Archive, CheckCircle2, Eye, Search, XCircle } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';
import { ConfirmDialog, EmptyState, ErrorState, PageSkeleton, StatusBadge } from './AdminUI';
import { useToast as useAdminToast } from '../../components/ui';
import { getCourses, moderateCourse } from './adminApi';
import { PageHeading } from './AdminUsersPage';

export default function AdminCoursesPage() {
  const [filters, setFilters] = useState({ search: '', status: '' });
  const [state, setState] = useState({ loading: true, rows: [], error: false });
  const [decision, setDecision] = useState(null);
  const [details, setDetails] = useState(null);
  const toast = useAdminToast();
  const load = useCallback(signal => getCourses(filters, signal).then(result => setState({ loading: false, rows: result.data || [], error: false })).catch(() => { if (!signal?.aborted) setState({ loading: false, rows: [], error: true }); }), [filters]);
  useEffect(() => { const controller = new AbortController(); const timer = setTimeout(() => load(controller.signal), 250); return () => { clearTimeout(timer); controller.abort(); }; }, [load]);
  const confirm = async () => { const reason = decision.action === 'reject' ? window.prompt('Provide a rejection reason') : null; if (decision.action === 'reject' && !reason) return; try { await moderateCourse(decision.course.id, decision.action, reason); toast({ message: `Course ${decision.action}d successfully.` }); setDecision(null); await load(); } catch (error) { toast({ type: 'error', message: error.response?.data?.message || 'Course moderation failed.' }); } };
  if (state.loading) return <PageSkeleton/>;
  if (state.error) return <ErrorState retry={load}/>;
  return <div className="space-y-6"><PageHeading title="Course management" description="Review the full catalog and operate the existing moderation workflow."/><div className="grid gap-3 rounded-2xl border bg-white p-4 sm:grid-cols-[1fr_220px]"><label className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><input className="field w-full pl-10" placeholder="Search courses" value={filters.search} onChange={e => setFilters({ ...filters, search: e.target.value })}/></label><select className="field" value={filters.status} onChange={e => setFilters({ ...filters, status: e.target.value })}><option value="">All statuses</option>{['draft','pending_review','published','rejected','archived'].map(status => <option key={status} value={status}>{status.replace('_',' ')}</option>)}</select></div>{state.rows.length ? <div className="grid gap-4 xl:grid-cols-2">{state.rows.map(course => <article key={course.id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><div className="flex flex-wrap items-center gap-2"><h3 className="text-lg font-extrabold">{course.title}</h3><StatusBadge value={course.status}/></div><p className="mt-1 text-sm text-slate-500">{course.instructor?.name} · {course.category?.name}</p></div><button onClick={() => setDetails(course)} className="rounded-lg border p-2" aria-label="View course"><Eye className="h-4 w-4"/></button></div><p className="mt-4 line-clamp-2 text-sm leading-6 text-slate-600">{course.short_description}</p><div className="mt-5 flex flex-wrap items-center gap-2 border-t pt-4">{course.status === 'pending_review' && <><Action icon={CheckCircle2} label="Approve" onClick={() => setDecision({ course, action: 'approve' })}/><Action icon={XCircle} label="Reject" danger onClick={() => setDecision({ course, action: 'reject' })}/></>}{course.status !== 'archived' && <Action icon={Archive} label="Archive" onClick={() => setDecision({ course, action: 'archive' })}/>}<span className="ml-auto text-xs font-bold text-slate-400">{course.enrollments_count || 0} enrollments</span></div></article>)}</div> : <EmptyState title="No courses found"/>}<ConfirmDialog open={Boolean(decision)} title={`${decision?.action} ${decision?.course.title}?`} description="This action uses the existing course moderation workflow and will be recorded on the course." confirmLabel={decision?.action} danger={decision?.action === 'reject'} onConfirm={confirm} onClose={() => setDecision(null)}/>{details && <CourseDetails course={details} close={() => setDetails(null)}/>}</div>;
}
const Action = ({ icon: Icon, label, danger, onClick }) => <button onClick={onClick} className={`inline-flex items-center gap-1.5 rounded-lg px-3 py-2 text-sm font-bold ${danger ? 'bg-red-50 text-red-700' : 'bg-slate-100 text-slate-700'}`}><Icon className="h-4 w-4"/>{label}</button>;
function CourseDetails({ course, close }) { return <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/50 p-4"><div className="w-full max-w-2xl rounded-3xl bg-white p-7 shadow-2xl"><button onClick={close} className="float-right rounded-lg border px-3 py-1">Close</button><StatusBadge value={course.status}/><h2 className="mt-3 text-2xl font-black">{course.title}</h2><p className="mt-2 text-slate-500">By {course.instructor?.name} ({course.instructor?.email})</p><p className="mt-6 leading-7 text-slate-700">{course.description}</p><div className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="Level" value={course.level}/><Metric label="Reviews" value={course.review_count}/><Metric label="Rating" value={course.average_rating}/></div></div></div>; }
const Metric = ({ label, value }) => <div className="rounded-xl bg-slate-50 p-4"><small className="uppercase text-slate-400">{label}</small><strong className="mt-1 block capitalize">{value}</strong></div>;
